clear
echo -e "\e[1;36m"
echo "  _____                    __  __           "
echo " |_   _|__ _ __ _ __ ___  \ \/ /___  _   _ "
echo "   | |/ _ \ '__| '_ \` _ \  \  // _ \| | | |"
echo "   | |  __/ |  | | | | | | /  \ (_) | |_| |"
echo "   |_|\___|_|  |_| |_| |_|/_/\_\___/ \__,_|"
echo -e "\e[1;33m"
echo "╔══════════════════════════════════════════╗"
echo "║   \e[1;32m● \e[1;35mW E L C O M E   T O   T E R M U X \e[1;32m●\e[1;33m   ║"
echo "╠══════════════════════════════════════════╣"
echo -e "║ \e[1;36m● Author: \e[1;33mYourName                      \e[1;33m║"
echo -e "║ \e[1;36m● Contact: \e[1;34m@YourTelegram                \e[1;33m║"
echo -e "║ \e[1;36m● GitHub: \e[1;31mgithub.com/YourUsername       \e[1;33m║"
echo "╚══════════════════════════════════════════╝"
echo -e "\e[1;32m"
echo " [ + ] Available Commands:"
echo -e " \e[1;33m● help \e[0m- Show basic commands"
echo -e " \e[1;33m● menu \e[0m- Show tool menu"
echo -e " \e[1;33m● update \e[0m- Update packages"
echo -e "\e[1;35m"
echo "➤ Type 'start' to begin your journey!"
echo -e "\e[0m"